version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

  api:
    image: backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env:ro
      - static:/app/wwwroot
      
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "80:80"
      - "443:80" # Внешний порт 8080 ведет на Nginx фронтенда
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
  static: